version: 2
updates:
<<<<<<< Updated upstream
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
=======
  - package-ecosystem: 'npm' # Adjust this if you're using a different package manager
    directory: '/' # Location of the package.json file
    schedule:
      interval: 'daily' # Check for updates daily
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 5
>>>>>>> Stashed changes
