/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PenButton {
    }
    interface PenInput {
        "description": string;
        "label": string;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPenButtonElement extends Components.PenButton, HTMLStencilElement {
    }
    var HTMLPenButtonElement: {
        prototype: HTMLPenButtonElement;
        new (): HTMLPenButtonElement;
    };
    interface HTMLPenInputElement extends Components.PenInput, HTMLStencilElement {
    }
    var HTMLPenInputElement: {
        prototype: HTMLPenInputElement;
        new (): HTMLPenInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pen-button": HTMLPenButtonElement;
        "pen-input": HTMLPenInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PenButton {
    }
    interface PenInput {
        "description"?: string;
        "label"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pen-button": PenButton;
        "pen-input": PenInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pen-button": LocalJSX.PenButton & JSXBase.HTMLAttributes<HTMLPenButtonElement>;
            "pen-input": LocalJSX.PenInput & JSXBase.HTMLAttributes<HTMLPenInputElement>;
        }
    }
}
