/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PenButton {
    }
    interface PenCombobox {
    }
    interface PenComboboxOption {
        /**
          * The state of the option.
         */
        "selected": boolean;
        /**
          * The value of the option.
         */
        "value": string;
    }
    interface PenInput {
        "description": string;
        "label": string;
        "value": string;
    }
}
declare global {
    interface HTMLPenButtonElement extends Components.PenButton, HTMLStencilElement {
    }
    var HTMLPenButtonElement: {
        prototype: HTMLPenButtonElement;
        new (): HTMLPenButtonElement;
    };
    interface HTMLPenComboboxElement extends Components.PenCombobox, HTMLStencilElement {
    }
    var HTMLPenComboboxElement: {
        prototype: HTMLPenComboboxElement;
        new (): HTMLPenComboboxElement;
    };
    interface HTMLPenComboboxOptionElement extends Components.PenComboboxOption, HTMLStencilElement {
    }
    var HTMLPenComboboxOptionElement: {
        prototype: HTMLPenComboboxOptionElement;
        new (): HTMLPenComboboxOptionElement;
    };
    interface HTMLPenInputElement extends Components.PenInput, HTMLStencilElement {
    }
    var HTMLPenInputElement: {
        prototype: HTMLPenInputElement;
        new (): HTMLPenInputElement;
    };
    interface HTMLElementTagNameMap {
        "pen-button": HTMLPenButtonElement;
        "pen-combobox": HTMLPenComboboxElement;
        "pen-combobox-option": HTMLPenComboboxOptionElement;
        "pen-input": HTMLPenInputElement;
    }
}
declare namespace LocalJSX {
    interface PenButton {
    }
    interface PenCombobox {
    }
    interface PenComboboxOption {
        /**
          * The state of the option.
         */
        "selected"?: boolean;
        /**
          * The value of the option.
         */
        "value"?: string;
    }
    interface PenInput {
        "description"?: string;
        "label"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "pen-button": PenButton;
        "pen-combobox": PenCombobox;
        "pen-combobox-option": PenComboboxOption;
        "pen-input": PenInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pen-button": LocalJSX.PenButton & JSXBase.HTMLAttributes<HTMLPenButtonElement>;
            "pen-combobox": LocalJSX.PenCombobox & JSXBase.HTMLAttributes<HTMLPenComboboxElement>;
            "pen-combobox-option": LocalJSX.PenComboboxOption & JSXBase.HTMLAttributes<HTMLPenComboboxOptionElement>;
            "pen-input": LocalJSX.PenInput & JSXBase.HTMLAttributes<HTMLPenInputElement>;
        }
    }
}
